apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-server-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-server-front
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: app-server-front
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: app-server-front
        image: canopit.azurecr.io/app-server:icici2
        ports:
        - containerPort: 8080
        args: ["tail","-f","-n","+1","tomcat-9.0.10/logs/catalina.out"]
        env:
        - name: REDIS
          value: "azure"
---
apiVersion: v1
kind: Service
metadata:
  name: app-server-front
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: app-server-front
