apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-server-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-server-front
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: app-server-front
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: app-server-front
        image: canopi.azurecr.io/app-server:icici1
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 800m
          limits:
            cpu: 900m
        env:
        - name: REDIS
          value: "azure"
---
apiVersion: v1
kind: Service
metadata:
  name: app-server-front
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: app-server-front
